### ISSUE TITLE
Problem compiling the "add-qt5-branch" with MSVC2010

### ISSUE THREAD

**Issue by rdeterre** [commontk/PythonQt#13]
Hi, 

I'm pretty sure that this issue has a lot to do with my bad understanding of CMake. I'd like to compile PythonQt with Qt5. After cloning the "add-qt5-branch", I started Cmake-gui, set the source code directory to the newly downloaded branch and pressed 'Configure'.

This returns the following error :

```
CMake Error in CMakeLists.txt:
  A logical block opening on the line
    C:/Users/Me/Desktop/PythonQt-add-qt5-support/CMakeLists.txt:30 (foreach)
  is not closed.
```

This lets me think that there may be a missing `endforeach` around line 33 in CMakeFile.txt, but since it is in a block of code for Qt versions less than 5, I added the following line just above the 'Build options' block to compile with Qt5 :

```
set(PythonQt_QT_VERSION "5")
```

I've only set `PythonQt_wrap_QtCore` to true, and the `Qt5Core_DIR` accordingly, and the QMake configure step now returns :

```
CMake Error at CMakeLists.txt:244 (qt5_wrap_ui):
  Unknown CMake command "qt5_wrap_ui".
```

Is there something I can do to make this work ?

Thanks

**Comment by binbao** [comment]
what's your qt version? Since qt5.2, it won't use "qt5_wrap_ui", see the qt doc here: http://qt-project.org/doc/qt-5/cmake-manual.html

**Comment by jcfr** [comment]
@binbao @rdeterre Just to let you know that Qt5 support has been integrated in PR #39

If you have a chance, any feedback would be appreciated. 

In the mean time, I am closing this issue.

Thanks
Jc
