### ISSUE TITLE
cannot override a non-deleted 

### ISSUE THREAD

**Issue by hjmjohnson** [commontk/PythonQt#20]
This issue occurs when building with c++11 on Mac 10.9 with clang compilers.

Hans

In file included from /Users/johnsonhj/src/Slicer-11/CTK-build/PythonQt/generated_cpp/com_trolltech_qt_gui/com_trolltech_qt_gui1.cpp:1:
/Users/johnsonhj/src/Slicer-11/CTK-build/PythonQt/generated_cpp/com_trolltech_qt_gui/com_trolltech_qt_gui1.h:378:7: error: deleted function '~PythonQtPublicPromoter_QClipboard' cannot override a non-deleted function
class PythonQtPublicPromoter_QClipboard : public QClipboard
      ^
/usr/local/Cellar/qt/4.8.6/include/QtGui/qclipboard.h:68:5: note: overridden virtual function is here
    ~QClipboard();
    ^
1 error generated.
make[5]: **\* [CMakeFiles/PythonQt.dir/generated_cpp/com_trolltech_qt_gui/com_trolltech_qt_gui1.cpp.o] Error 1
make[4]: **\* [CMakeFiles/PythonQt.dir/all] Error 2
make[3]: **\* [all] Error 2
make[2]: **\* [PythonQt-cmake/src/PythonQt-stamp/PythonQt-install] Error 2
make[1]: **\* [CMakeFiles/PythonQt.dir/all] Error 2
make: **\* [all] Error 2

**Comment by hjmjohnson** [comment]
FYI:  https://github.com/mwoehlke-kitware/PythonQt.git release-5 does not fix this issue.

**Comment by hjmjohnson** [comment]
From: Jean-Christophe Fillion-Robin jchris.fillionr@kitware.com
Date: Monday, March 31, 2014 at 3:12 PM
To: Hans Johnson hans-johnson@uiowa.edu
Cc: Slicer Development slicer-devel@bwh.harvard.edu
Subject: Re: [slicer-devel] CTK: Slicer clang c++11 build

Hi Hans, 

Considering the class is "promoting" the object so that it can be "public", I am not sure what is the right course of action. May be PythonQt should be refactored ? Is there a way to ignore that specific error ?

Would also suggest to discuss this on the PythonQt mailing list.

Hth
Jc

On Sat, Mar 29, 2014 at 12:18 PM, Johnson, Hans J hans-johnson@uiowa.edu wrote:
Slicer can not build with clang and c++11 due to an new CTK error that is found.

I believe this is a real problem.  The issue is that the destructor for Qclipboard() is declared as private, and therefore it should not be a base classs.

Regards,
Hans

[  1%] Building CXX object CMakeFiles/PythonQt.dir/generated_cpp/com_trolltech_qt_gui/com_trolltech_qt_gui1.cpp.o
In file included from /Users/johnsonhj/src/Slicer-newcpp/CTK-build/PythonQt/generated_cpp/com_trolltech_qt_gui/com_trolltech_qt_gui1.cpp:1:
/Users/johnsonhj/src/Slicer-newcpp/CTK-build/PythonQt/generated_cpp/com_trolltech_qt_gui/com_trolltech_qt_gui1.h:378:7: error: deleted function '~PythonQtPublicPromoter_QClipboard' cannot override a non-deleted function
class PythonQtPublicPromoter_QClipboard : public QClipboard
      ^
/Library/Frameworks/QtGui.framework/Headers/qclipboard.h:68:5: note: overridden virtual function is here
    ~QClipboard();
    ^
1 error generated.
make[5]: **\* [CMakeFiles/PythonQt.dir/generated_cpp/com_trolltech_qt_gui/com_trolltech_qt_gui1.cpp.o] Error 1
make[4]: **\* [CMakeFiles/PythonQt.dir/all] Error 2
make[3]: **\* [all] Error 2
make[2]: **\* [PythonQt-cmake/src/PythonQt-stamp/PythonQt-install] Error 2
make[1]: **\* [CMakeFiles/PythonQt.dir/all] Error 2
make: **\* [all] Error 2

**Comment by mwoehlke-kitware** [comment]
I pushed a fix for this: see mwoehlke-kitware/PythonQt@e463adc5a768.

I also reported it upstream: https://sourceforge.net/p/pythonqt/discussion/631393/thread/568fa0c0/

**Comment by billhoffman** [comment]
@jcfr, Did this fix get merged into ctk's pythonQt?

**Comment by jcfr** [comment]
Closing. This has been addressed upstream.

See https://github.com/commontk/PythonQt/blob/welcome/README.md to learn about the available branches.
