### ISSUE TITLE
QVector3D "!=" is missing

### ISSUE THREAD

**Issue by iestynne** [commontk/PythonQt#21]
The "!=" operator is missing from the metadata for QVector3D. Unfortunately, PythonQtInstanceWrapper_richcompare does not assert when asked to call this operator - it simply returns "True" in all cases! Cue mysterious vector math bugs :)

I looked at the PythonQt generator code, but couldn't figure out why "==/**eq**" was working, but "!=/**ne**" was not.

**Comment by jcfr** [comment]
Thanks for the report :+1: 

In the mean time, feel free to submit a pull request to patch the generated wrappers and report the issue upstream: http://sourceforge.net/p/pythonqt/mailman/

**Comment by florianlink** [comment]
This has been fixed in PythonQt on svn trunk a long time ago.

**Comment by jcfr** [comment]
Thanks for the update. In the next few days, I will finalize update of our fork and provide you with a list of patches that could potentially be integrated upstream.

**Comment by jcfr** [comment]
Closing. Issue has been addressed  upstream.
