### ISSUE TITLE
Crash in PythonQt::cleanup()

### ISSUE THREAD

**Issue by patmarion** [commontk/PythonQt#30]
I can reproduce this using system installed Python 2.7 and Qt 4.8 on my Ubuntu 14.04 desktop and Mac laptop (using homebrew python 2.7 and  qt 4.8).

I could try to put together a pure c++ example to reproduce the crash.  For now, I am reproducing the crash by launching the python console widget provided by ctkPythonConsole.cpp and entering these lines:

> > > from PythonQt import QtCore
> > > x = QtCore.QFile.ReadOnly

The crash occurs when the application exits.  The crash is not specific to the QFile.ReadOnly flag.  Referencing any flag will lead to a crash later. It seems like this crash would have been encountered by other people, so maybe the issue is only on my end?  Same crash in Debug or Release mode.  My PythonQt is configured with only these enabled:

PythonQt_Wrap_Qtcore
PythonQt_Wrap_Qtgui

Here is gdb backtrace:
#0  0x00007ffff5ce9721 in ?? () from /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
#1  0x00007ffff506a2a3 in PythonQtObjectPtr::~PythonQtObjectPtr (this=0xbcebd0, __in_chrg=<optimized out>)

```
at /home/pat/source/drc/drc/software/externals/pod-build/src/PythonQt/src/PythonQtObjectPtr.cpp:52
```
#2  0x00007ffff4fa1110 in PythonQtMemberInfo::~PythonQtMemberInfo (this=0xbcebb8, __in_chrg=<optimized out>)

```
at /home/pat/source/drc/drc/software/externals/pod-build/src/PythonQt/src/PythonQtClassInfo.h:45
```
#3  0x00007ffff4fa51cd in QHashNode<QByteArray, PythonQtMemberInfo>::~QHashNode (this=0xbceba0, __in_chrg=<optimized out>) at /usr/include/qt4/QtCore/qhash.h:216
#4  0x00007ffff4fa5224 in QHash<QByteArray, PythonQtMemberInfo>::deleteNode2 (node=0xbceba0) at /usr/include/qt4/QtCore/qhash.h:521
#5  0x00007ffff6ab0609 in QHashData::free_helper(void (_)(QHashData::Node_)) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4
#6  0x00007ffff4fa3330 in QHash<QByteArray, PythonQtMemberInfo>::freeData (this=0x84d2a0, x=0xbcb2d0) at /usr/include/qt4/QtCore/qhash.h:570
#7  0x00007ffff4fa1628 in QHash<QByteArray, PythonQtMemberInfo>::~QHash (this=0x84d2a0, __in_chrg=<optimized out>) at /usr/include/qt4/QtCore/qhash.h:283
#8  0x00007ffff4f9b25e in PythonQtClassInfo::~PythonQtClassInfo (this=0x84d2a0, __in_chrg=<optimized out>)

```
at /home/pat/source/drc/drc/software/externals/pod-build/src/PythonQt/src/PythonQtClassInfo.cpp:70
```
#9  0x00007ffff4fba118 in PythonQtPrivate::~PythonQtPrivate (this=0x87f320, __in_chrg=<optimized out>)

```
at /home/pat/source/drc/drc/software/externals/pod-build/src/PythonQt/src/PythonQt.cpp:333
```
#10 0x00007ffff4fba3a2 in PythonQtPrivate::~PythonQtPrivate (this=0x87f320, __in_chrg=<optimized out>)

```
at /home/pat/source/drc/drc/software/externals/pod-build/src/PythonQt/src/PythonQt.cpp:341
```
#11 0x00007ffff4fba005 in PythonQt::~PythonQt (this=0x827280, __in_chrg=<optimized out>) at /home/pat/source/drc/drc/software/externals/pod-build/src/PythonQt/src/PythonQt.cpp:322
#12 0x00007ffff4fba06e in PythonQt::~PythonQt (this=0x827280, __in_chrg=<optimized out>) at /home/pat/source/drc/drc/software/externals/pod-build/src/PythonQt/src/PythonQt.cpp:324
#13 0x00007ffff4fb9ab5 in PythonQt::cleanup () at /home/pat/source/drc/drc/software/externals/pod-build/src/PythonQt/src/PythonQt.cpp:249
#14 0x00007ffff7bce057 in ctkAbstractPythonManager::~ctkAbstractPythonManager (this=0x7fffffffd630, __in_chrg=<optimized out>)

```
at /home/pat/source/drc/drc/software/externals/pod-build/src/ctkPythonConsole/src/ctkAbstractPythonManager.cpp:90
```
#15 0x000000000040129a in main (argc=1, argv=0x7fffffffd778) at /home/pat/source/drc/drc/software/externals/pod-build/src/ctkPythonConsole/src/main.cpp:37

**Comment by jcfr** [comment]
Closing. This has been addressed by @msmolens in https://github.com/commontk/PythonQt/compare/d60734955d6e9dc887ecc4b56c0d481baf813a59...0c2ba518714d63df820798f9eb7c18a0fbc7fbd2
