### ISSUE TITLE
Qt 5.6 support

### ISSUE THREAD

**Issue by rasgo-cc** [commontk/PythonQt#41]
Hi,

Is patched-5 version supposed to work with Qt 5.6?
The readme says "Add Qt5 support" but while bulding I get the message saying this version is not supported and that I need Qt4

**Comment by jcfr** [comment]
@cidadao Thanks for the note. Support for Qt5 has just been merged into `patched-5` branch.
See https://github.com/commontk/PythonQt/commit/cb38ae51cf526164e4f4a3ecf92fd4501aed1aab

Let us know how it works.

Have a good day, 
Jc

**Comment by dtmoodie** [comment]
I'm using the mentioned branch against Qt5.6.  However I get a cmake error for missing Qt5WebKitWidgets which seems to have been replaced by QtWebEngineWidgets.

**Comment by jcfr** [comment]
Thanks for the note.

It means we need to update the build system to support Qt 5.6

There is also some changes from upstream that would need to be considered. See https://sourceforge.net/p/pythonqt/code/409/log/?path=/trunk

If you would like to work  on a patch,  let me know and I would be happy to help you out.

Thanks
Jc

**Comment by rasgo-cc** [comment]
I just gave up trying to get it to work with Q5.6. I read somewhere that PythonQt is supported only until Qt 5.4 (major changes in some widget components?). So that's what I did. Installed Qt5.4 and now I have PythonQt working like a charm.
