### ISSUE TITLE
patched-8 missing Qt private includes

### ISSUE THREAD

**Issue by cwilling** [commontk/PythonQt#54]
The CMakeLists.txt in patched-8 branch is missing the inclusion of private Qt headers, resulting in build failure (using qt5-5.7.1). I have sent pull request #53 to fix that - it copies the relevant entry verbatim from the patched-7 version.

**Comment by jcfr** [comment]
Closing. Fix has been integrated into `patched-8` branch as https://github.com/commontk/PythonQt/commit/0401ec7b847ba1781d86a234b6258ed9a062763d
