### ISSUE TITLE
How to deal with multiple py files?

### ISSUE THREAD

**Issue by 461353349** [commontk/PythonQt#55]
There are two py files is defined in the resources.  The 2th file call the 1th file. How to deal with it. 

If codes are as followings, No correct result meet.

  // evaluate the python script which is defined in the resources
  mainModule.evalFile(":writefile.py");
  mainModule.evalFile(":GettingStarted.py");

**Comment by jcfr** [comment]
Thanks for the report.

Since this repo is only a convenient fork to main patches related to CMake support for PythonQt, I suggest you ask your question on the project mailing list: https://sourceforge.net/p/pythonqt/discussion/
