### ISSUE TITLE
qt4.8.6 with patched-7

### ISSUE THREAD

**Issue by nvuaille** [commontk/PythonQt#61]
Patched-7 is supposed to work with qt4 but at configure time I have:
```
CMake Error at CMakeLists.txt:366 (add_library):
  Cannot find source file:

    generated_cpp_48/PythonQt_QtBindings.cpp
```
And indeed, on branch patched-7 the folder generated_cpp_48 was removed by commit d27f8b96243635ae4729e4ec9373c39d7d865d99

@jcfr  : Do you have an idea to fix this ? My project should build with a recent qt5 (OK with patched-7) and if may be with qt 4.8

I'm on debian buster with cmake 3.9.5 and gcc 7.2

**Comment by jcfr** [comment]
hi @nvuaille , 

First, you can find description of the "maintained" branches here: https://github.com/commontk/PythonQt#which-branch-

>  on branch patched-7 the folder generated_cpp_48

branch is not maintained, I would not recommend using it

For Qt4, `patched-6` should be used
For Qt5, `patched-8` should be used


If you would like your system to support both Qt4 and Qt5, following an approach similar to what is done here would be best: https://github.com/commontk/CTK/blob/9604eda05cbe1016395b7e197b8fde6b2d1181e9/CMakeExternals/PythonQt.cmake

**Comment by nvuaille** [comment]
Thanks for your advice @jcfr !

I will use patched 8 and probably drop support for qt4 =)
