### ISSUE TITLE
Error with python 3.7 : Require native threads 

### ISSUE THREAD

**Issue by jeromedias86** [commontk/PythonQt#79]
I'm in Ubuntu 18.04.5 and working with the branch `patched-8`
I get this issue when I use python 3.7 or higher from my system : 
`/usr/include/python3.7m/pythread.h:122:5: error: #error "Require native threads. See https://bugs.python.org/issue31370"`

This issue doesn't occur when I use a lower python version (python 3.6.12 works for me)

The problem seems to come from this line where `_POSIX_THREAD` is unset : https://github.com/commontk/PythonQt/blob/fae2301264529b4c8c85ee6e285f9605176471f0/src/PythonQtPythonInclude.h#L38

If I comment this line all is working for me, but don't know if it's the best solution to fix this issue.

**Comment by jcfr** [comment]
Closing. Support for newer Python versions has been integrated in `patched-9` branch.
